---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "observer-app"
    static_configs:
      - targets: ["app:8000"]
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /metrics
